#page title
page_title                                : GU Assistant                              # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                           # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/icon_512x512.png                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : GU Assistant                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Improve your God's Unchained skills. Rank higher, win more.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 
your_link                                 : 
your_city                                 : 
email_address                             : guassistant@icloud.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          : GUAssistant



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Opponent's deck prediction
    description                           : Automatically predicts your opponent's deck based on their game history.
    fontawesome_icon_name                 : magic
    
  - title                                 : Load deck via deck code
    description                           : Load the deck of your opponent manually. This is great for tournaments with open deck lists.
    fontawesome_icon_name                 : play-circle

  - title                                 : In-battle card tracking
    description                           : Tracks which cards you and your opponent have still left in your decks
    fontawesome_icon_name                 : sync

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Question List                            Edit, add or remove FAQ questions to be presented.
questions                                 :

  - title                                 : Is it free?
    answer                                : Yes, currently it is an alpha version where all functionality if free.
    
  - title                                 : I get a security warning. Is it safe to use?
    answer                                : Yes. There might be security warnings as we dont distribute versions via the official app stores. This allows us to incorporate feedback much faster at a low cost. If this is a strong reason to not try the application, please write us at guassistant@icloud.com. 

  - title                                 : Does Gods Unchained see this as cheating?
    answer                                : No, there have been similar applications in the past where the team did not see this as violating existing policies.

  - title                                 : Isn't this hacking?
    answer                                : No, we essentially just automate the process of note taking during a battle. You can achieve the same with pen and paper manually.

  - title                                 : How does this work?
    answer                                : We make use of open information you collect while playing the game. Similar to the in-game battle log, the purpose of this application is it to help you building better skills and ultimately have more fun playing.
  
  - title                                 : # Question Title
    answer                                : # Question Answer


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#0E151F"
cover_overlay_transparency                : 0.8

body_background_color                     : "#ffffff"

link_color                                : "#7891AD"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F6F6F6"
feature_icons_background_color            : "#70B9CA"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
